# Generated by Django 4.0.2 on 2022-02-14 04:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 4, 38, 20, 379058, tzinfo=utc)),
        ),
    ]
